services:
  cupsback:
    image: cypagcupsback:latest
    # build:
    #   context: .
    #   dockerfile: ./back/Dockerfile
    environment:
      - TOKEN_SECRET
      - USER_BD
      - PASS_BD
      - SERVER_BD
      - NAME_BD
      - PORT
      - APP
      - APP_NAME
    ports:
      - 3001:3001

  cupsfront:
    image: cypagcupsfront:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    ports:
      - 47082:80
    # environment:
    #   - REACT_APP_API_URL
    depends_on:
      - cupsback
